### ISSUE TITLE
Performance degradation going from 2.0 -> 3.0+

### ISSUE THREAD

**Issue by danielnordh** [s0nerik/fast_contacts#29]
Have happily been using version 1.1.1 for several years.
As part of general dependency updates I installed the 3.1.4 (not yet on latest Flutter).

I noticed a severe degradation in speed when fetching and displaying contacts and started isolating the version that had the biggest impact.

It was when going from 2.0 to 3.0 that the issue started. I am still digging into my own code to see if it affects the issue, but 2.0 and below is fast.

The only code change I had to make going to 3.0 was to use .getAllContacts() instead of .allContacts:

`List<Contact> userContacts = await FastContacts.getAllContacts();`

The changelog is not very specific about the changes that happened there, but clearly something behaves very differently and adds visible time (1-3 seconds) to the loading which previously was not noticeable.

Should I be using the field filter to get the same performance as before?

**Comment by s0nerik** [comment]
Most probably, the reason you're seeing a performance degradation switching from v2 to v3 is because the v3 introduced batched result propagation.

Previously, all contacts were returned from the MethodChannel as a result of a single call. This was the fastest way for returning the results from the MethodChannel and it worked well. Unfortunately, though, this approach resulted in a noticeable UI lag on really huge contact lists since MethodChannel data marshaling/unmarshaling happens on the main isolate. This was especially noticeable on slower phones.

To solve this issue, v3 started returning the already-fetched contacts via multiple MethodChannel calls to give Flutter a chance to render the frames between those calls. In my tests, it resulted in a negligible (a couple of milliseconds) increase in the overall contacts fetching delay, while keeping the test app buttery smooth even on a huge contacts list.

I suspect that your app's event queue may be quite busy during the contacts fetch, which forces each next batch to be returned much later. You may try adjusting the `batchSize` parameter to a much larger value to somewhat return to the previous blocking approach if your UX requirements allow for it.

**Comment by danielnordh** [comment]
Thanks for the quick response.

After debugging further, comparing time to show UI between 2.0 and 3.0 I managed to isolate it to one line of code that was outside fast_contacts. 

I was fetching the contacts inside a provider. This provider was invalidated before loading the contacts list view, but the multiple calls in 3.0 must behave differently as it seems the view was reloading and therefore triggering the invalidation multiple times, delaying the eventual data availability from the provider.

Moving the invalidation higher up the tree solved the issue and I have now managed to update to 3.1.4 with no performance difference.

FYI, I was fetching 944 contacts, and when measuring the time in detail there was not much in it between 2.0 and 3.0 when I had fixed my issue.

Thanks again!

ps. Minor comment, when installing the pod for iOS the command line updates for cocoa pod reports it as 0.0.1 regardless of version: 

`Installing fast_contacts (0.0.1)`
